import { ReactNode } from "react";
import { CartProvider } from "@/contexts/CartContext";
import { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Order Food Online from India's Best Food Delivery Service | Swiggy",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
